[package]
name = "alkash3d-editor"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.31", default-features = false, features = ["default_fonts", "glow", "wgpu"]}
egui = "0.31"
egui-wgpu = "0.31"
egui_extras = { version = "0.31", features = ["image"] }
uuid = { version = "1.6", features = ["v4", "serde"] }
anyhow = "1.0"
rfd = "0.17.2"
tobj = "4.0"
which = "8.0.2"
rand = "0.10.1"
rayon = "1.12.0"
wgpu = "27.0.0"
winit = "0.30.13"
bytemuck = { version = "1", features = ["derive"] }
lru = "0.18.0"
[build-dependencies]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[profile.dev]
opt-level = 1

[lib]
name = "alkash3d_editor"
path = "src/lib.rs"

[[bin]]
name = "alkash3d-editor"
path = "src/main.rs"