[package]
name = "alkash3d-inertial"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32"
rayon = "1.12"
parking_lot = "0.12"

[features]
default = ["fortran"]
fortran = ["dep:cc", "dep:which"]
pure_rust = []

[build-dependencies]
cc = { version = "1.2", optional = true }
which = { version = "8.0", optional = true }

[lib]
name = "inertial"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1